POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "name":"gayathiri",
    "email":"gayu34@gmail.com",
    "contact":"1234567890",
    "age":"22",
    "jobRole":"Developer"
}